name: Build ANGLE - Android ARM64 (Rely on gclient sync for NDK/SDK) - 逐步验证

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_angle_android_arm64_gclient_ndk:
    runs-on: ubuntu-latest

    env:
      DEPOT_TOOLS_PATH: angle/third_party/depot_tools
      ANDROID_NDK_VERSION: r26d
      TARGET_ANDROID_API_LEVEL: 34
      DEPOT_TOOLS_WINTOOLCHAIN: 0
      NINJA_JOBS: $(nproc)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # 确保没有额外的配置，例如 sparse checkout
        with:
          repository: 你自己的用户名/ci  # 你自己的用户名替换成你自己的用户名
          sparse-checkout-cone-mode: true # 使用 sparse checkout cone mode
      - name: Verify Checkout
        run: |
          pwd
          ls -al # 查看仓库的根目录
          ls -al angle || true # 确认 angle 目录是否存在，如果不存在则忽略错误
          ls -al angle/third_party || true # 确认 angle/third_party 目录是否存在，如果不存在则忽略错误

      #  调整 depot_tools 缓存的路径
      - name: Install depot_tools and Cache
        id: cache-depot-tools
        uses: actions/cache@v4
        with:
          path: angle/third_party/depot_tools
          key: depot_tools-${{ runner.os }}
          restore-keys: |
            depot_tools-

      - name: Install depot_tools if not cached
        if: steps.cache-depot-tools.outputs.cache-hit != 'true'
        working-directory: angle/third_party
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git

      - name: Verify Install - depot_tools
        working-directory: angle/third_party
        run: |
          pwd
          ls -al depot_tools
          ls -al depot_tools/bootstrap_python3 # 确认 bootstrap_python3 存在
          echo "DEPOT_TOOLS env var: $DEPOT_TOOLS"
          echo "PATH env var: $PATH"
          echo "depot_tools installation verified."

      - name: Verify depot_tools in PATH
        working-directory: angle
        run: |
          echo "PATH from ENV file: $PATH"
          export PATH="$PATH:$(pwd)/third_party/depot_tools"
          which gclient
          gclient --version
          echo "gclient is accessible in PATH."

      - name: Create ANGLE directory
        run: mkdir -p angle

      - name: Configure gclient
        working-directory: angle
        run: gclient config https://chromium.googlesource.com/angle/angle.git

      - name: Verify Configure - gclient
        working-directory: angle
        run: |
          ls -al
          cat .gclient
          echo "gclient configuration verified."

      - name: Sync ANGLE Source Code (Using gclient sync for initial checkout)
        id: gclient-sync
        working-directory: angle
        if: steps.cache-angle-source.outputs.cache-hit != 'true' #只有在没有源码缓存时才 sync
        run: |
          echo "Starting gclient sync..."
          date
          export PATH="$PATH:$(pwd)/third_party/depot_tools"
          gclient sync -j$(nproc)
          date
          echo "gclient sync completed."

      - name: Cache ANGLE Source Code (gclient sync)
        id: cache-angle-source
        uses: actions/cache@v4
        if: steps.gclient-sync.outcome == 'success' # 只有在上一步成功时才缓存
        with:
          path: angle
          key: angle-source-${{ runner.os }}-${{ hashFiles('angle/.gclient', 'angle/DEPS') }}
          restore-keys: |
            angle-source-${{ runner.os }}-

      - name: Install Build Dependencies (Using install-build-deps.py)
        id: install-build-deps
        working-directory: angle
        run: |
          export PATH="$PATH:$(pwd)/third_party/depot_tools"
          sudo apt-get update
          python3 angle/build/install-build-deps.py --no-prompt
          # 创建标记文件
          touch .install-build-deps-success

      - name: Cache Install Build Dependencies
        id: cache-install-build-deps
        uses: actions/cache@v4
        with:
          path: angle
          key: install-build-deps-${{ runner.os }}-${{ hashFiles('angle/build/install-build-deps.py') }}
          restore-keys: |
            install-build-deps-${{ runner.os }}-

      # --- 缓存 Android SDK/NDK ---
      - name: Cache Android SDK/NDK
        id: cache-android-sdk-ndk
        uses: actions/cache@v4
        if: steps.cache-install-build-deps.outputs.cache-hit != 'true'
        with:
          path: android_sdk_ndk  #  需要根据 install-android-sdk.py 实际安装位置来调整
          key: android-sdk-ndk-${{ runner.os }}-${{ env.ANDROID_NDK_VERSION }}-${{ env.TARGET_ANDROID_API_LEVEL }}
          restore-keys: |
            android-sdk-ndk-${{ runner.os }}-
      #  --------------------------

      - name: Install vpython deps
        working-directory: angle # 修改
        if: steps.cache-android-sdk-ndk.outputs.cache-hit != 'true'
        run: |
          # Activate depot_tools environment AGAIN. This is CRUCIAL
          #source depot_tools/bootstrap_python3  # 移除
          #export PATH="$PATH:$(pwd)/depot_tools" # 移除
          #  创建缓存目录