name: Sync ANGLE Source Code

on:
  workflow_dispatch:  #  允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: Gong-Mi/ci  #  检出 workflow 配置文件

      - name: Install depot_tools and Cache
        id: cache-depot-tools
        uses: actions/cache@v4
        with:
          path: depot_tools
          key: depot_tools-${{ runner.os }}
          restore-keys: |
            depot_tools-

      - name: Install depot_tools if not cached
        if: steps.cache-depot-tools.outputs.cache-hit != 'true'
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git

      - name: Verify Install - depot_tools
        run: |
          pwd
          ls -al depot_tools
          ls -al depot_tools/bootstrap_python3
          echo "depot_tools installation verified."

      - name: Create ANGLE directory
        run: mkdir -p angle

      - name: Configure gclient
        working-directory: angle
        run: |
          export PATH="$PATH:$(pwd)/../depot_tools"
          gclient config https://chromium.googlesource.com/angle/angle.git

      - name: Sync ANGLE Source Code (gclient sync)
        id: gclient-sync
        working-directory: angle
        run: |
          echo "Starting gclient sync..."
          date
          export PATH="$PATH:$(pwd)/../depot_tools"
          gclient sync -j$(nproc)
          date
          echo "gclient sync completed."

      - name: Cache ANGLE Source Code (gclient sync)
        id: cache-angle-source
        uses: actions/cache@v4
        with:
          path: angle
          key: angle-source-${{ runner.os }}-${{ hashFiles('angle/.gclient', 'angle/DEPS') }}
          restore-keys: |
            angle-source-${{ runner.os }}-