      - name: Install Build Dependencies  #  直接运行本地脚本，提前执行
        run: |
          export PATH="$PATH:$(pwd)/depot_tools"  #  depot_tools 和 install-build-deps.py 在同一仓库根目录
          python install-build-deps.py  #  直接运行根目录下的脚本，路径正确

      - name: Create ANGLE directory
        run: mkdir -p angle

      - name: Configure gclient
        working-directory: angle
        run: |
          export PATH="$PATH:$(pwd)/../depot_tools" #  angle 目录在 workflow 根目录下， depot_tools 在 workflow 根目录下
          gclient config https://chromium.googlesource.com/angle/angle.git

      - name: Cache Install Build Dependencies #  缓存安装依赖后的状态，在 install-build-deps 之后
        id: cache-install-build-deps
        uses: actions/cache@v4
        with:
          path: angle  #  缓存 angle 目录，包含 install-build-deps.py 安装的依赖
          key: install-build-deps-${{ runner.os }}-${{ hashFiles('install-build-deps.py') }} #  重要: 缓存 Key 依赖于 install-build-deps.py 脚本自身
          restore-keys: |
            install-build-deps-${{ runner.os }}-